### ISSUE TITLE
Failed to npm install -g wififox on MacOS

### ISSUE THREAD

**Issue by laurent-d** [t-mullen/wififox#1]
Hi @t-mullen !! 
Your apps seems very promising but i can't install it on MacOs 10.15.5

➜  ~ npm install -g wififox

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/Users/xxxxxxxxxxxx/.nvm/versions/node/v10.19.0/bin/wififox -> /Users/xxxxxxxxxxxx/.nvm/versions/node/v10.19.0/lib/node_modules/wififox/main.js

> wififox@1.0.1 postinstall /Users/xxxxxxxxxxxx/.nvm/versions/node/v10.19.0/lib/node_modules/wififox
> electron-builder install-app-deps

sh: electron-builder: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! wififox@1.0.1 postinstall: `electron-builder install-app-deps`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the wififox@1.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxxxxxxxxx/.npm/_logs/2020-07-10T09_19_13_858Z-debug.log
➜  ~ electron-builder install-app-deps
zsh: command not found: electron-builder

Install electron-builder doesn't help

Hope it helps

Regards

**Comment by t-mullen** [comment]
Thanks for trying out WiFiFox. Can you try `npm install -g electron-builder`?

**Comment by laurent-d** [comment]
Thomas i tried without good result..

My node version v10.19.0
Npm version v6.13.4

➜  ~ npm install -g wififox   
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/Users/xxxxxxxxxxxx/.nvm/versions/node/v10.19.0/bin/wififox -> /Users/xxxxxxxxxxxx/.nvm/versions/node/v10.19.0/lib/node_modules/wififox/main.js

> wififox@1.0.1 postinstall /Users/xxxxxxxxxxxx/.nvm/versions/node/v10.19.0/lib/node_modules/wififox
> electron-builder install-app-deps

  • electron-builder  version=22.7.0
  • loaded configuration  file=package.json ("build" field)
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed and version ("^9.0.5") is not fixed in project.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wififox@1.0.1 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wififox@1.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lxxxxxxxxxxxx/.npm/_logs/2020-07-10T20_56_57_926Z-debug.log

**Comment by laurent-d** [comment]
@t-mullen ok it's work now after fixing dev dependency in local >
"devDependencies": {
    "electron": "9.0.5"
  }
source : https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-547115107

**Comment by t-mullen** [comment]
They've also been fixed in the published version. Try 1.0.5. Thanks for catching that!

**Comment by francescopupillo** [comment]
Hi,
I've been having a similar issue on my OS Sonoma M1 macbook air:

1898 error code 1
1899 error path /usr/local/lib/node_modules/wififox/node_modules/electron
1900 error command failed
1901 error command sh -c node install.js
1902 error HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
1902 error     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/wififox/node_modules/got/source/as-stream.js:35:24)
1902 error     at EventEmitter.emit (node:events:518:28)
1902 error     at module.exports (/usr/local/lib/node_modules/wififox/node_modules/got/source/get-response.js:22:10)
1902 error     at ClientRequest.handleResponse (/usr/local/lib/node_modules/wififox/node_modules/got/source/request-as-event-emitter.js:155:5)
1902 error     at Object.onceWrapper (node:events:633:26)
1902 error     at ClientRequest.emit (node:events:530:35)
1902 error     at origin.emit (/usr/local/lib/node_modules/wififox/node_modules/@szmarczak/http-timer/source/index.js:37:11)
1902 error     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
1902 error     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
1902 error     at TLSSocket.socketOnData (node:_http_client:535:22)
1903 verbose exit 1
1904 timing npm Completed in 2068ms
1905 verbose unfinished npm timer reify 1709596029359
1906 verbose unfinished npm timer reify:build 1709596030838
1907 verbose unfinished npm timer build 1709596030838
1908 verbose unfinished npm timer build:deps 1709596030838
1909 verbose unfinished npm timer build:run:postinstall 1709596030847
1910 verbose unfinished npm timer build:run:postinstall:node_modules/wififox 1709596030847
1911 verbose unfinished npm timer build:run:postinstall:node_modules/wififox/node_modules/electron 1709596030849
1912 verbose code 1

Can someone help me? 
Thank you so much
