### ISSUE TITLE
Installation on Win10

### ISSUE THREAD

**Issue by nbctcp** [t-mullen/wififox#2]
Could you please explain on what required and steps to install on WIN10
tq

**Comment by t-mullen** [comment]
What kind of issues are you having with the steps in the README?

**Comment by nbctcp** [comment]
README said install using NPM, but that one I think for Linux
What software need to be installed on WIN10 and what file need to be opened first
I install node.js on WIN10 and open node.js or index.html but nothing happen
no pop up windows appear

**Comment by t-mullen** [comment]
NPM is for Windows as well. https://phoenixnap.com/kb/install-node-js-npm-on-windows

I'll be releasing binaries for all platforms eventually.

**Comment by t-mullen** [comment]
If anyone has issues with Windows installation with NPM, please make a new issue.
