### ISSUE TITLE
Menubar

### ISSUE THREAD

**Issue by ReconBurrito** [t-mullen/wififox#6]
When I run, "sudo wififox" nothing happens. When my vpn is up and I run it, it selects the port and lets my connect to the open wifi.
I am using Private Internet Access and normally I bypass on port 53 however this network is a beefy boi so it selects port 8080 after running, "sudo wififox".

I'm running Windows 10.
Isn't there exposed to be a popup or it references a "menubar"? I don't see it.

**Comment by Yavzz** [comment]
You must use linux.This project is for linux users.
